jdk:
  - openjdk11

language: java
install:
  - ""
script:
  - javac simplified/Keyserver.java
  - javac imap/*.java
  - javac smap/*.java
    #  - jshell --class-path key-2.7-exe.jar -v key-ci.jshell
  - java -jar key-2.7-citool.jar simplified/Keyserver.java
  - java -jar key-2.7-citool.jar --proof-path imap imap/project.key

