jdk:
  - openjdk11

language: java
install:
  - wget -O ci-tool.jar https://key-project.org/ci-tool
script:
  - javac simplified/Keyserver.java
  - javac -sourcepath imap_classpath imap/*.java
  - javac smap/*.java
  - java -jar ci-tool.jar simplified/Keyserver.java
  - cd imap ; java -jar ../ci-tool.jar @.ci-args.txt 

